### ISSUE TITLE
make install error: cannot import name '_RNA' from partially initialized module 'RNA'

### ISSUE THREAD

**Issue by gprezza** [ViennaRNA/ViennaRNA#186]
I am trying to install locally from source. I run:
```
tar -zxvf ViennaRNA-2.5.1.tar.gz
cd ViennaRNA-2.5.1
./configure --prefix=/home/gprezza/bin/ViennaRNA
make install
```

The last command fails after a while with the following message (last few lines in the terminal):
```
  GEN      RNA/__init__.py
  GEN      RNA/_RNANone
  GEN      RNA/__pycache__/__init__.cpython-311.pyc
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named '_RNA'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gprezza/bin/ViennaRNA-2.5.1/interfaces/Python/RNA/__init__.py", line 11, in <module>
    from . import _RNA
ImportError: cannot import name '_RNA' from partially initialized module 'RNA' (most likely due to a circular import) (/home/gprezza/bin/ViennaRNA-2.5.1/interfaces/Python/RNA/__init__.py)
make[2]: *** [Makefile:1042: RNA/__pycache__/__init__.cpython-311.pyc] Error 1
make[2]: Leaving directory '/home/gprezza/bin/ViennaRNA-2.5.1/interfaces/Python'
make[1]: *** [Makefile:642: install-recursive] Error 1
make[1]: Leaving directory '/home/gprezza/bin/ViennaRNA-2.5.1/interfaces'
make: *** [Makefile:692: install-recursive] Error 1
```

Couldn't find anything around that solves this, would appreciate any help.

**Comment by gprezza** [comment]
Turns out it's an issue with the Python version in my conda environment. I downgraded to Python 3.6 and could complete the installation.

Seems to be fixed in https://github.com/ViennaRNA/ViennaRNA/pull/173
